export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const FETCH_PROPERTIES = "FETCH_PROPERTIES";
export const ADD_PROPERTIES = "ADD_PROPERTIES";
export const DELETE_PROPERTIES = "DELETE_PROPERTIES";
export const UPDATE_PROPERTIES = "UPDATE_PROPERTIES";
