export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
//Properties constants
export const FETCH_PROPERTIES = "FETCH_PROPERTIES";
export const ADD_PROPERTIES = "ADD_PROPERTIES";
export const DELETE_PROPERTIES = "DELETE_PROPERTIES";
export const UPDATE_PROPERTIES = "UPDATE_PROPERTIES";
export const FILTER_PROPERTIES = "FILTER_PROPERTIES";
export const SELECT_PROPERTY = "SELECT_PROPERTY";
export const LIKED_PROPERTIES = "LIKED_PROPERTIES";
